import express from "express";
import { signup, login, logout, updateProfile, updatePublicKey } from "../controllers/auth.controller.js";
import { protectRoute } from "../middleware/auth.middleware.js";
import { arcjetProtection, localRateLimit } from "../middleware/arcjet.middleware.js";
import User from "../models/User.js";
const router = express.Router();
// router.use(arcjetProtection);
router.use(localRateLimit);
router.post("/signup",signup);
router.post("/login", login);
router.post("/logout", logout);
router.put("/update-profile", protectRoute, updateProfile);
router.put("/update-public-key", protectRoute, updatePublicKey);
router.get("/check", protectRoute, (req,res)=> res.status(200).json(req.user));
export default router;